Dev l4
QwertyForcee/projectManagementSystem pull request #3
Opened 2022-04-27 13:07 UTC by QwertyForcee

Кажется я готов сдавать весь проект

https://qwertyforcee.github.io/

email: "user@gmail.com"
password: "user"

Это типо поиск по номеру тикета в "репозитории проекта" на гитхабе, если предположить что разработчик в сообщении коммита оставляет номер тикета, то можно такой поиск сделать когда тикет смотришь. Но для примера я статичный поиск со словом "fix" сделал.
![image](https://user-images.githubusercontent.com/62138442/165523632-181b3a34-cd53-4cdb-9726-953d9c10d1f2.png)

здесь по количеству коммитов чарт с реальной инфой.

![image](https://user-images.githubusercontent.com/62138442/165524361-abd9e404-121f-4b49-a13f-cd52199f0b38.png)

2022-05-08 13:12 UTC, katetushkan requested changes
Looks good. But board management (addition / deletion) and drag'n'drop are not working for me.Is this ok?

2022-05-08 15:47 UTC, QwertyForcee commented
> Looks good. But board management (addition / deletion) and drag'n'drop are not working for me. Is this ok?

Если с телефона то драг'н'дроп не должен работать. Если вы с мака, то я могу пофиксить наверное, но тестить я не знаю где, у меня нету мака

2022-05-10 07:22 UTC, katetushkan commented
Not from mobile, from desktop Chrome/Safari/Mozilla.

2022-05-12 11:29 UTC, katetushkan requested changes
have u deploy?

2022-05-12 11:33 UTC, katetushkan commented
<img width="1437" alt="Screenshot 2022-05-12 at 13 30 37" src="https://user-images.githubusercontent.com/43992068/168065059-4517b0a1-2ee7-4fa7-91a5-91b10589e282.png">
<img width="1150" alt="Screenshot 2022-05-12 at 13 31 17" src="https://user-images.githubusercontent.com/43992068/168065167-7081132d-cf10-4a28-b5ad-20a7afbff3a0.png">
not clickable at all(((

drop still not working, even in Chrome(

2022-05-12 22:13 UTC, QwertyForcee commented
в общем проблема была в том , что когда перетаскивал тикет на другую колонку, и отпускал его, сначала шел ивент dragleave, за ним dragend. А в dragleave у меня была такая логика (испсользовался setTimeOut и в нем убирался класс с розовым фоном): 
![image](https://user-images.githubusercontent.com/62138442/168173408-782bf057-6ba4-4075-9e51-0986bcd1f087.png)

а в dragend искался элемент с таким классом, и по нему брался айди 
![image](https://user-images.githubusercontent.com/62138442/168176068-2effbefb-3bc3-4799-930c-1640ebb605c9.png)

На виндоус сначала срабатывал dragend где колонка розовая успешно находилась, а потом выполнялся код из setTimeOut , где розовая колонка становилась обычной. 

А на маке было наоборот, и в dragend уже не могла найтись нужная колонка. В фиксе я убрал сетТаймАут и по другому сделал.

2022-05-16 12:07 UTC, katetushkan approved these changes
Отлично, молодец, что пофиксили, <kbd>10</kbd> ваша.

2022-05-16 15:04 UTC, merged